/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/account-details`; params?: Router.UnknownInputParams; } | { pathname: `/driver-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/driver-registration`; params?: Router.UnknownInputParams; } | { pathname: `/driver-status`; params?: Router.UnknownInputParams; } | { pathname: `/email-info`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/phone-auth`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/shipments`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/user-info`; params?: Router.UnknownInputParams; } | { pathname: `/verify-code`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/account-details`; params?: Router.UnknownOutputParams; } | { pathname: `/driver-dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/driver-registration`; params?: Router.UnknownOutputParams; } | { pathname: `/driver-status`; params?: Router.UnknownOutputParams; } | { pathname: `/email-info`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/phone-auth`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/shipments`; params?: Router.UnknownOutputParams; } | { pathname: `/splash`; params?: Router.UnknownOutputParams; } | { pathname: `/user-info`; params?: Router.UnknownOutputParams; } | { pathname: `/verify-code`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/account-details${`?${string}` | `#${string}` | ''}` | `/driver-dashboard${`?${string}` | `#${string}` | ''}` | `/driver-registration${`?${string}` | `#${string}` | ''}` | `/driver-status${`?${string}` | `#${string}` | ''}` | `/email-info${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/phone-auth${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/shipments${`?${string}` | `#${string}` | ''}` | `/splash${`?${string}` | `#${string}` | ''}` | `/user-info${`?${string}` | `#${string}` | ''}` | `/verify-code${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/account-details`; params?: Router.UnknownInputParams; } | { pathname: `/driver-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/driver-registration`; params?: Router.UnknownInputParams; } | { pathname: `/driver-status`; params?: Router.UnknownInputParams; } | { pathname: `/email-info`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/phone-auth`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/shipments`; params?: Router.UnknownInputParams; } | { pathname: `/splash`; params?: Router.UnknownInputParams; } | { pathname: `/user-info`; params?: Router.UnknownInputParams; } | { pathname: `/verify-code`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
