name: Backoffice Build & Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files to debug
        run: |
          echo "Current directory:"
          pwd
          echo "Root directory contents:"
          ls -la
          echo "Backoffice directory contents:"
          ls -la backoffice/ || echo "backoffice directory not found"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backoffice
          file: ./backoffice/Dockerfile
          push: true
          tags: |
            ghcr.io/aybarci/yuklegeltaksi/backoffice:latest
            ghcr.io/aybarci/yuklegeltaksi/backoffice:${{ github.sha }}